receivers:
  otlp:
    protocols:
      grpc:
      http:

  filelog/backend-app:
    include: ["/var/log/backend-app/*.log"]
    start_at: beginning
    operators:
      - type: regex_parser
        regex: '^(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3}) \[(?P<thread>[^\]]+)\] \[trace_id=(?P<trace_id>[^\s]+) span_id=(?P<span_id>[^\]]+)\] (?P<level>\S+)\s+(?P<logger>[^\s]+) - (?P<message>.*)$'
        timestamp:
          # IMPORTANTE: leer el valor del grupo regex que está en attributes.<name>
          parse_from: attributes.ts
          layout_type: strptime
          # formato compatible con %d{yyyy-MM-dd HH:mm:ss.SSS} de Logback
          layout: "%Y-%m-%d %H:%M:%S.%L"

processors:
  batch:
  memory_limiter:
    check_interval: 5s
    limit_mib: 256

exporters:
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

  otlphttp/tempo:
    endpoint: http://tempo:4321
    tls:
      insecure: true

  logging:
    loglevel: info

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/tempo, logging]

    logs:
      receivers: [filelog/backend-app, otlp]
      processors: [memory_limiter, batch]
      exporters: [loki, logging]
