server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend-app
          __path__: /var/log/backend-app/*.log
